[tool.poetry]
name = "papa-boxes"
version = "0.1.0"
description = "_"
authors = ["Andrew"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
icecream = "^2.1.3"
pandas = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
